import { BadRequestException, ForbiddenException, Injectable, NotFoundException } from '@nestjs/common';
import { PrismaService } from '../../config/prisma.service';
import { CreateTicketDto, MessageDto, StatusDto, CreateRefundRequestDto } from './dto/support.dto';
import { SupportTicketStatus } from '@prisma/client';
@Injectable() export class SupportService { constructor(private prisma:PrismaService){}
 async createCustomer(customerId:string,d:CreateTicketDto){if(d.orderId){const o=await this.prisma.order.findUnique({where:{id:d.orderId}});if(!o||o.customerId!==customerId)throw new BadRequestException('Invalid order.')}return this.prisma.supportTicket.create({data:{customerId,orderId:d.orderId,subject:d.subject,description:d.description,messages:{create:{senderId:customerId,message:d.description,isAdmin:false}}},include:{messages:true}})}
 async createVendor(vendorUserId:string,d:CreateTicketDto){const v=await this.prisma.vendor.findUnique({where:{ownerUserId:vendorUserId},select:{id:true}});if(!v)throw new NotFoundException('No vendor profile found.');if(d.orderId){const o=await this.prisma.order.findUnique({where:{id:d.orderId},select:{vendorId:true}});if(!o||o.vendorId!==v.id)throw new BadRequestException('Invalid order for this store.')}return this.prisma.supportTicket.create({data:{vendorId:v.id,orderId:d.orderId,subject:d.subject,description:d.description,messages:{create:{senderId:vendorUserId,message:d.description,isAdmin:false}}},include:{messages:true}})}
 mineCustomer(id:string){return this.prisma.supportTicket.findMany({where:{customerId:id},include:{messages:{orderBy:{createdAt:'asc'}}},orderBy:{updatedAt:'desc'}})}
 async mineVendor(id:string){const v=await this.prisma.vendor.findUnique({where:{ownerUserId:id},select:{id:true}});if(!v)throw new NotFoundException('No vendor profile found.');return this.prisma.supportTicket.findMany({where:{vendorId:v.id},include:{messages:{orderBy:{createdAt:'asc'}},order:{select:{orderNumber:true}}},orderBy:{updatedAt:'desc'}})}
 async getCustomer(id:string,ticketId:string){const t=await this.prisma.supportTicket.findUnique({where:{id:ticketId},include:{messages:{orderBy:{createdAt:'asc'}}}});if(!t)throw new NotFoundException('Ticket not found.');if(t.customerId!==id)throw new ForbiddenException('Not allowed.');return t}
 async getVendor(id:string,ticketId:string){const v=await this.prisma.vendor.findUnique({where:{ownerUserId:id},select:{id:true}});const t=await this.prisma.supportTicket.findUnique({where:{id:ticketId},include:{messages:{orderBy:{createdAt:'asc'}},order:{select:{orderNumber:true}}}});if(!v||!t||t.vendorId!==v.id)throw new ForbiddenException('Not allowed.');return t}
 async messageOwner(id:string,kind:'customer'|'vendor',ticketId:string,d:MessageDto){if(kind==='customer')await this.getCustomer(id,ticketId);else await this.getVendor(id,ticketId);return this.prisma.supportMessage.create({data:{ticketId,senderId:id,message:d.message,isAdmin:false}})}
 listAdmin(){return this.prisma.supportTicket.findMany({include:{customer:true,vendor:{select:{id:true,storeName:true}},order:true,messages:{orderBy:{createdAt:'asc'}}},orderBy:{updatedAt:'desc'}})}
 async messageAdmin(adminId:string,ticketId:string,d:MessageDto){const t=await this.prisma.supportTicket.findUnique({where:{id:ticketId}});if(!t)throw new NotFoundException('Ticket not found.');return this.prisma.supportMessage.create({data:{ticketId,senderId:adminId,message:d.message,isAdmin:true}})}
 async status(id:string,d:StatusDto){if(!(Object.values(SupportTicketStatus) as string[]).includes(d.status))throw new BadRequestException('Invalid ticket status.');return this.prisma.supportTicket.update({where:{id},data:{status:d.status as SupportTicketStatus}})}

 async refundRequests(customerId:string){return this.prisma.refund.findMany({where:{order:{customerId}},orderBy:{createdAt:'desc'},include:{order:{select:{id:true,orderNumber:true,status:true}},payment:{select:{provider:true,reference:true,status:true}}}})}
 async createRefundRequest(customerId:string,d:CreateRefundRequestDto){const order=await this.prisma.order.findFirst({where:{id:d.orderId,customerId},include:{payments:{where:{status:'SUCCESS'},orderBy:{createdAt:'desc'},take:1}}});if(!order)throw new NotFoundException('Order not found.');const payment=order.payments[0];if(!payment)throw new BadRequestException('No successful payment was found for this order.');const existing=await this.prisma.refund.findFirst({where:{orderId:order.id,status:{in:['REQUESTED','PROCESSING']}}});if(existing)throw new BadRequestException('A refund request is already being reviewed for this order.');const amount=d.amount??payment.amount;if(amount<=0||amount>payment.amount)throw new BadRequestException('Refund amount is invalid.');return this.prisma.refund.create({data:{paymentId:payment.id,orderId:order.id,amount,reason:d.reason.trim(),requestedByUserId:customerId,status:'REQUESTED'},include:{order:{select:{id:true,orderNumber:true,status:true}},payment:{select:{provider:true,reference:true,status:true}}}})}
}