import { BadRequestException, ConflictException, Injectable, NotFoundException } from '@nestjs/common';
import { PrismaService } from '../../config/prisma.service';
import { vendorForUser } from '../../common/utils/vendor-context';
import { AuditLogService } from '../audit/audit-log.service';
import { CreateCampaignDto, UpdateCampaignDto } from './dto/vendor-advertising.dto';
@Injectable() export class VendorAdvertisingService {
 constructor(private prisma:PrismaService, private audit:AuditLogService){}
 private async vendor(ownerUserId:string){return vendorForUser(this.prisma, ownerUserId);}
 async list(ownerUserId:string){const v=await this.vendor(ownerUserId);return this.prisma.vendorAdvertisingCampaign.findMany({where:{vendorId:v.id},include:{outlet:{select:{id:true,name:true}},products:{include:{product:{select:{id:true,name:true,sku:true}}}}},orderBy:{createdAt:'desc'}})}
 async create(ownerUserId:string,d:CreateCampaignDto){const v=await this.vendor(ownerUserId);const starts=new Date(d.startsAt),ends=new Date(d.endsAt);if(ends<=starts)throw new BadRequestException('End time must be after start time.');if(d.outletId){const o=await this.prisma.outlet.findFirst({where:{id:d.outletId,vendorId:v.id}});if(!o)throw new NotFoundException('Outlet not found.');}const products=d.productIds?.length?await this.prisma.product.findMany({where:{vendorId:v.id,id:{in:d.productIds}},select:{id:true}}):[];if(d.productIds?.length!==products.length)throw new NotFoundException('One or more selected products were not found.');const r=await this.prisma.vendorAdvertisingCampaign.create({data:{vendorId:v.id,outletId:d.outletId||undefined,name:d.name.trim(),objective:d.objective,budgetAmount:d.budgetAmount,startsAt:starts,endsAt:ends,products:{create:products.map(p=>({productId:p.id}))}}});await this.audit.record({actorId:ownerUserId,action:'vendor.advertising.create',entityType:'VendorAdvertisingCampaign',entityId:r.id,after:{name:r.name,budgetAmount:r.budgetAmount}});return r;}
 async update(ownerUserId:string,id:string,d:UpdateCampaignDto){const v=await this.vendor(ownerUserId);const before=await this.prisma.vendorAdvertisingCampaign.findFirst({where:{id,vendorId:v.id}});if(!before)throw new NotFoundException('Campaign not found.');const starts=d.startsAt?new Date(d.startsAt):before.startsAt, ends=d.endsAt?new Date(d.endsAt):before.endsAt;if(ends<=starts)throw new BadRequestException('End time must be after start time.');if(d.outletId){const o=await this.prisma.outlet.findFirst({where:{id:d.outletId,vendorId:v.id}});if(!o)throw new NotFoundException('Outlet not found.');}const r=await this.prisma.$transaction(async tx=>{if(d.productIds){await tx.vendorAdvertisingCampaignProduct.deleteMany({where:{campaignId:id}});const ps=await tx.product.findMany({where:{vendorId:v.id,id:{in:d.productIds}},select:{id:true}});if(ps.length!==d.productIds!.length)throw new NotFoundException('One or more selected products were not found.');await tx.vendorAdvertisingCampaignProduct.createMany({data:ps.map(x=>({campaignId:id,productId:x.id}))});}return tx.vendorAdvertisingCampaign.update({where:{id},data:{name:d.name?.trim(),budgetAmount:d.budgetAmount,startsAt:starts,endsAt:ends,outletId:d.outletId===null?null:d.outletId}})});await this.audit.record({actorId:ownerUserId,action:'vendor.advertising.update',entityType:'VendorAdvertisingCampaign',entityId:id,before,after:r});return r;}
 async setStatus(ownerUserId:string,id:string,status:'ACTIVE'|'PAUSED'|'ENDED'){const v=await this.vendor(ownerUserId);const c=await this.prisma.vendorAdvertisingCampaign.findFirst({where:{id,vendorId:v.id}});if(!c)throw new NotFoundException('Campaign not found.');if(status==='ACTIVE'&&c.budgetAmount<=c.spendAmount)throw new BadRequestException('Campaign budget has been exhausted.');return this.prisma.vendorAdvertisingCampaign.update({where:{id},data:{status}})}
 async stats(ownerUserId:string){const rows=await this.list(ownerUserId);const sum=(k:string)=>rows.reduce((a:any,r:any)=>a+Number(r[k]||0),0);const spend=sum('spendAmount'),revenue=sum('revenueAmount'),clicks=sum('clicks'),impressions=sum('impressions');return {campaigns:rows.length,active:rows.filter(r=>r.status==='ACTIVE').length,scheduled:rows.filter(r=>new Date(r.startsAt)>new Date()).length,totalSpend:spend,totalRevenue:revenue,impressions,clicks,conversions:sum('conversions'),ctr:impressions?clicks/impressions*100:0,roas:spend?revenue/spend:0};}
}
