CREATE TYPE "NotificationType" AS ENUM ('ORDER','DELIVERY','PAYMENT','PAYOUT','INVENTORY','PROMOTION','REVIEW','ACCOUNT','SYSTEM');
CREATE TYPE "NotificationPreferenceChannel" AS ENUM ('PUSH','EMAIL','SMS');
ALTER TABLE "notifications" ADD COLUMN "type" "NotificationType" NOT NULL DEFAULT 'SYSTEM';
ALTER TABLE "notifications" ADD COLUMN "readAt" TIMESTAMP(3);
CREATE INDEX "notifications_userId_channel_readAt_idx" ON "notifications"("userId","channel","readAt");
CREATE INDEX "notifications_userId_type_createdAt_idx" ON "notifications"("userId","type","createdAt");
CREATE TABLE "notification_preferences" ("id" TEXT NOT NULL,"userId" TEXT NOT NULL,"type" "NotificationType" NOT NULL,"channel" "NotificationPreferenceChannel" NOT NULL,"enabled" BOOLEAN NOT NULL DEFAULT true,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "notification_preferences_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "notification_preferences_userId_type_channel_key" ON "notification_preferences"("userId","type","channel");
CREATE INDEX "notification_preferences_userId_type_idx" ON "notification_preferences"("userId","type");
ALTER TABLE "notification_preferences" ADD CONSTRAINT "notification_preferences_userId_fkey" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;
