from pathlib import Path

def replace_once(path, old, new):
    p=Path(path); text=p.read_text()
    if new in text: return
    if old not in text: raise SystemExit(f'Expected text not found in {path}: {old[:120]!r}')
    p.write_text(text.replace(old,new,1))

# Raw SQL must match Prisma's mapped lowercase table name.
p=Path('backend/src/modules/promotions/promotions.service.ts'); t=p.read_text(); t=t.replace(r'\"Promotion\"', r'\"promotions\"'); p.write_text(t)

replace_once('backend/src/modules/vendors/vendors.service.ts', "    return this.prisma.vendorDocument.create({ data: { vendorId: vendor.id, docType, fileUrl } });", "    const ownedFileUrl = await this.storage.getOwnedPublicImageUrl(ownerUserId, fileUrl);\n    return this.prisma.vendorDocument.create({ data: { vendorId: vendor.id, docType: docType.trim(), fileUrl: ownedFileUrl } });")
replace_once('backend/src/modules/vendors/vendors.service.ts', "  async setOpenStatus(ownerUserId: string, isOpen: boolean) {\n    const vendor = await this.getByOwner(ownerUserId);\n    if (vendor.status !== VendorStatus.APPROVED) {\n      throw new ForbiddenException('Only approved vendors can open for orders.');\n    }", "  async setOpenStatus(ownerUserId: string, isOpen: boolean) {\n    const vendor = await this.getByOwner(ownerUserId);\n    if (vendor.status !== VendorStatus.APPROVED) {\n      throw new ForbiddenException('Only approved vendors can open for orders.');\n    }\n    if (isOpen && vendor.holidayMode) throw new ForbiddenException('The store is in holiday mode. Disable holiday mode before opening.');\n    if (isOpen && vendor.temporaryClosureUntil && vendor.temporaryClosureUntil > new Date()) throw new ForbiddenException('The store is temporarily closed until the scheduled reopening time.');")
replace_once('backend/src/modules/vendors/vendors.service.ts', "  async setOperationalMode(ownerUserId: string, mode: 'holiday' | 'busy', enabled: boolean, busyPreparationTimeMinutes?: number) {\n    const vendor = await this.getByOwner(ownerUserId);\n    if (mode === 'busy') {", "  async setOperationalMode(ownerUserId: string, mode: 'holiday' | 'busy', enabled: boolean, busyPreparationTimeMinutes?: number) {\n    if (mode !== 'holiday' && mode !== 'busy') throw new BadRequestException('Invalid operational mode.');\n    if (typeof enabled !== 'boolean') throw new BadRequestException('enabled must be a boolean.');\n    if (busyPreparationTimeMinutes !== undefined && (!Number.isInteger(busyPreparationTimeMinutes) || busyPreparationTimeMinutes < 0)) throw new BadRequestException('Busy preparation time must be a non-negative integer.');\n    const vendor = await this.getByOwner(ownerUserId);\n    if (mode === 'busy') {")
replace_once('backend/src/modules/vendors/vendors.service.ts', "    if (!serviceArea) throw new NotFoundException('Service area not found.');\n\n    return this.prisma.vendor.create({", "    if (!serviceArea) throw new NotFoundException('Service area not found.');\n    if (serviceArea.status !== 'ACTIVE') throw new BadRequestException('This service area is not currently active.');\n    const vendorType = await this.prisma.vendorType.findUnique({ where: { id: dto.vendorTypeId } });\n    if (!vendorType) throw new NotFoundException('Vendor type not found.');\n    if (!vendorType.isActive) throw new BadRequestException('This vendor type is not currently available.');\n\n    return this.prisma.vendor.create({")
replace_once('backend/src/modules/vendors/vendors.service.ts', "    if (!serviceArea) throw new NotFoundException('Service area not found.');\n\n    return this.prisma.vendorLocation.upsert({", "    if (!serviceArea) throw new NotFoundException('Service area not found.');\n    if (serviceArea.status !== 'ACTIVE') throw new BadRequestException('This service area is not currently active.');\n\n    return this.prisma.vendorLocation.upsert({")
replace_once('backend/src/modules/vendors/vendor-onboarding.service.ts', "  async submit(userId: string) {\n    const v = await this.vendor(userId);\n    const snap = await this.snapshot(v.id);", "  async submit(userId: string) {\n    const v = await this.vendor(userId);\n    const lockedStatuses: VendorStatus[] = [VendorStatus.APPROVED, VendorStatus.SUSPENDED];\n    if (lockedStatuses.includes(v.status)) throw new ForbiddenException('Onboarding cannot be submitted while the store is active or suspended.');\n    const snap = await this.snapshot(v.id);")
replace_once('backend/src/modules/finance/vendor-finance.service.ts', "          discountAmount: true,\n          items: {", "          discountAmount: true,\n          promotionId: true,\n          promotion: { select: { vendorId: true } },\n          items: {")
replace_once('backend/src/modules/finance/vendor-finance.service.ts', "      this.prisma.order.aggregate({\n        where: {\n          vendorId: vendor.id,\n          createdAt: date,\n          status: { notIn: [OrderStatus.DELIVERED, OrderStatus.CANCELLED, OrderStatus.FAILED, OrderStatus.REFUNDED] },\n        },\n        _sum: { totalAmount: true },\n        _count: { id: true },\n      }),", "      this.prisma.order.findMany({\n        where: { vendorId: vendor.id, createdAt: date, status: { notIn: [OrderStatus.DELIVERED, OrderStatus.CANCELLED, OrderStatus.FAILED, OrderStatus.REFUNDED] } },\n        select: { discountAmount: true, promotionId: true, promotion: { select: { vendorId: true } }, items: { select: { subtotalAmount: true, commissionAmountSnapshot: true } } },\n      }),")
replace_once('backend/src/modules/finance/vendor-finance.service.ts', "    const vendorEarnings = delivered.reduce(\n      (s, o) => {\n        const merchandise = o.items.reduce((sum, item) => sum + item.subtotalAmount, 0);\n        const itemCommission = o.items.reduce((sum, item) => sum + item.commissionAmountSnapshot, 0);\n        return s + Math.max(0, merchandise - itemCommission);\n      },\n      0,\n    );", "    const vendorEarningForOrder = (o: any) => {\n      const merchandise = o.items.reduce((sum: number, item: any) => sum + item.subtotalAmount, 0);\n      const discount = Math.min(Math.max(0, o.discountAmount ?? 0), merchandise);\n      const vendorFunded = Boolean(o.promotionId && o.promotion?.vendorId);\n      const netBase = vendorFunded ? Math.max(0, merchandise - discount) : merchandise;\n      const grossCommission = o.items.reduce((sum: number, item: any) => sum + item.commissionAmountSnapshot, 0);\n      const commission = vendorFunded && merchandise > 0 ? Math.min(grossCommission, Math.round(grossCommission * netBase / merchandise)) : grossCommission;\n      return Math.max(0, netBase - commission);\n    };\n    const vendorEarnings = delivered.reduce((s, o) => s + vendorEarningForOrder(o), 0);\n    const pendingBalance = pendingOrders.reduce((s, o) => s + vendorEarningForOrder(o), 0);")
replace_once('backend/src/modules/finance/vendor-finance.service.ts', "      pendingBalance: Math.max(0, pendingOrders._sum.totalAmount ?? 0),\n      pendingOrderCount: pendingOrders._count.id,", "      pendingBalance: Math.max(0, pendingBalance),\n      pendingOrderCount: pendingOrders.length,")
replace_once('backend/src/modules/finance/vendor-finance.service.ts', "    const paidOut = payouts.filter(p => p.status === VendorPayoutStatus.PAID).reduce((s, p) => s + p.amount, 0);", "    const paidOut = payouts.filter(p => p.status === VendorPayoutStatus.PAID && p.createdAt >= date.gte && p.createdAt <= date.lte).reduce((s, p) => s + p.amount, 0);")
replace_once('backend/src/modules/products/product-options.service.ts', "    const max = dto.maxSelections ?? 1;\n    this.validateBounds(min, max);", "    const max = dto.maxSelections ?? 1;\n    if ((dto.isRequired ?? false) && min < 1) throw new BadRequestException('Required option groups must require at least one selection.');\n    this.validateBounds(min, max);")
replace_once('backend/src/modules/products/product-options.service.ts', "    const max = dto.maxSelections ?? group.maxSelections;\n    this.validateBounds(min, max);", "    const max = dto.maxSelections ?? group.maxSelections;\n    const nextRequired = dto.isRequired ?? group.isRequired;\n    if (nextRequired && min < 1) throw new BadRequestException('Required option groups must require at least one selection.');\n    this.validateBounds(min, max);")
replace_once('backend/src/modules/vendors/team.service.ts', "    const passwordHash = await bcrypt.hash(dto.password, 12);\n    const result = await this.prisma.$transaction(async tx => {\n      const user = existing || await tx.user.create({ data: { fullName: invite.fullName, email: invite.email, phone: invite.phone, passwordHash, role: UserRole.VENDOR } });\n      if (existing) {\n        if (existing.role !== UserRole.VENDOR) throw new BadRequestException('This account cannot accept a vendor team invitation.');\n        await tx.user.update({ where: { id: existing.id }, data: { passwordHash, isActive: true } });\n      }", "    const passwordHash = existing ? null : await bcrypt.hash(dto.password, 12);\n    const result = await this.prisma.$transaction(async tx => {\n      const claimed = await tx.vendorStaffInvitation.updateMany({ where: { id: invite.id, acceptedAt: null, expiresAt: { gt: new Date() } }, data: { acceptedAt: new Date() } });\n      if (claimed.count !== 1) throw new BadRequestException('This invitation is invalid or has already been accepted.');\n      const user = existing || await tx.user.create({ data: { fullName: invite.fullName, email: invite.email, phone: invite.phone, passwordHash: passwordHash!, role: UserRole.VENDOR } });\n      if (existing) {\n        if (existing.role !== UserRole.VENDOR) throw new BadRequestException('This account cannot accept a vendor team invitation.');\n        if (!existing.isActive) await tx.user.update({ where: { id: existing.id }, data: { isActive: true } });\n      }")
replace_once('backend/src/modules/vendors/team.service.ts', "      await tx.vendorStaffInvitation.update({ where: { id: invite.id }, data: { acceptedAt: new Date() } });\n      return { user, member };", "      return { user, member };")
print('batch29 consolidated vendor audit patch applied')
