from pathlib import Path
p=Path('backend/src/modules/auth/auth.service.ts')
s=p.read_text(encoding='utf-8-sig')
old='''    await this.prisma.$transaction([\n      this.prisma.user.update({\n        where: {\n          id: row.userId,\n        },\n        data: {\n          passwordHash,\n        },\n      }),\n      this.prisma.passwordResetToken.update({\n        where: {\n          id: row.id,\n        },\n        data: {\n          usedAt: new Date(),\n        },\n      }),\n      this.prisma.refreshToken.updateMany({\n        where: {\n          userId: row.userId,\n          revoked: false,\n        },\n        data: {\n          revoked: true,\n        },\n      }),\n    ]);\n'''
new='''    await this.prisma.$transaction(async (tx) => {\n      const consumed = await tx.passwordResetToken.updateMany({\n        where: {\n          id: row.id,\n          usedAt: null,\n          expiresAt: { gt: new Date() },\n        },\n        data: { usedAt: new Date() },\n      });\n\n      if (consumed.count !== 1) {\n        throw new BadRequestException('Invalid or expired reset token.');\n      }\n\n      await tx.user.update({\n        where: { id: row.userId },\n        data: { passwordHash },\n      });\n\n      await tx.refreshToken.updateMany({\n        where: { userId: row.userId, revoked: false },\n        data: { revoked: true },\n      });\n    });\n'''
if old not in s: raise SystemExit('password reset transaction block not found')
s=s.replace(old,new,1)
old2='''    await this.prisma.$transaction([\n      this.prisma.verificationToken.update({\n        where: {\n          id: row.id,\n        },\n        data: {\n          usedAt: new Date(),\n        },\n      }),\n      this.prisma.user.update({\n        where: {\n          id: row.userId,\n        },\n        data:\n          type ===\n          VerificationTokenType.EMAIL_VERIFICATION\n            ? { isEmailVerified: true }\n            : { isPhoneVerified: true },\n      }),\n    ]);\n'''
new2='''    await this.prisma.$transaction(async (tx) => {\n      const consumed = await tx.verificationToken.updateMany({\n        where: {\n          id: row.id,\n          usedAt: null,\n          expiresAt: { gt: new Date() },\n        },\n        data: { usedAt: new Date() },\n      });\n\n      if (consumed.count !== 1) {\n        throw new BadRequestException('Invalid or expired verification token.');\n      }\n\n      await tx.user.update({\n        where: { id: row.userId },\n        data:\n          type === VerificationTokenType.EMAIL_VERIFICATION\n            ? { isEmailVerified: true }\n            : { isPhoneVerified: true },\n      });\n    });\n'''
if old2 not in s: raise SystemExit('verification transaction block not found')
s=s.replace(old2,new2,1)
p.write_text(s,encoding='utf-8')
