from pathlib import Path

def replace_once(path, old, new):
    p=Path(path); text=p.read_text()
    if new in text: return
    if old not in text: raise SystemExit(f'Expected text not found in {path}: {old[:120]!r}')
    p.write_text(text.replace(old,new,1))

replace_once('backend/src/modules/finance/vendor-finance.service.ts', "          discountAmount: true,\n          items: {", "          discountAmount: true,\n          promotionId: true,\n          promotion: { select: { vendorId: true } },\n          items: {")
replace_once('backend/src/modules/finance/vendor-finance.service.ts', "      this.prisma.order.aggregate({\n        where: {\n          vendorId: vendor.id,\n          createdAt: date,\n          status: { notIn: [OrderStatus.DELIVERED, OrderStatus.CANCELLED, OrderStatus.FAILED, OrderStatus.REFUNDED] },\n        },\n        _sum: { totalAmount: true },\n        _count: { id: true },\n      }),", "      this.prisma.order.findMany({\n        where: { vendorId: vendor.id, createdAt: date, status: { notIn: [OrderStatus.DELIVERED, OrderStatus.CANCELLED, OrderStatus.FAILED, OrderStatus.REFUNDED] } },\n        select: { discountAmount: true, promotionId: true, promotion: { select: { vendorId: true } }, items: { select: { subtotalAmount: true, commissionAmountSnapshot: true } } },\n      }),")
replace_once('backend/src/modules/finance/vendor-finance.service.ts', "    const vendorEarnings = delivered.reduce(\n      (s, o) => {\n        const merchandise = o.items.reduce((sum, item) => sum + item.subtotalAmount, 0);\n        const itemCommission = o.items.reduce((sum, item) => sum + item.commissionAmountSnapshot, 0);\n        return s + Math.max(0, merchandise - itemCommission);\n      },\n      0,\n    );", "    const vendorEarningForOrder = (o: any) => {\n      const merchandise = o.items.reduce((sum: number, item: any) => sum + item.subtotalAmount, 0);\n      const discount = Math.min(Math.max(0, o.discountAmount ?? 0), merchandise);\n      const vendorFunded = Boolean(o.promotionId && o.promotion?.vendorId);\n      const netBase = vendorFunded ? Math.max(0, merchandise - discount) : merchandise;\n      const grossCommission = o.items.reduce((sum: number, item: any) => sum + item.commissionAmountSnapshot, 0);\n      const commission = vendorFunded && merchandise > 0 ? Math.min(grossCommission, Math.round(grossCommission * netBase / merchandise)) : grossCommission;\n      return Math.max(0, netBase - commission);\n    };\n    const vendorEarnings = delivered.reduce((s, o) => s + vendorEarningForOrder(o), 0);\n    const pendingBalance = pendingOrders.reduce((s, o) => s + vendorEarningForOrder(o), 0);")
replace_once('backend/src/modules/finance/vendor-finance.service.ts', "      pendingBalance: Math.max(0, pendingOrders._sum.totalAmount ?? 0),\n      pendingOrderCount: pendingOrders._count.id,", "      pendingBalance: Math.max(0, pendingBalance),\n      pendingOrderCount: pendingOrders.length,")
replace_once('backend/src/modules/finance/vendor-finance.service.ts', "    const paidOut = payouts.filter(p => p.status === VendorPayoutStatus.PAID).reduce((s, p) => s + p.amount, 0);", "    const paidOut = payouts.filter(p => p.status === VendorPayoutStatus.PAID && p.createdAt >= date.gte && p.createdAt <= date.lte).reduce((s, p) => s + p.amount, 0);")
print('batch28 vendor finance audit patch applied')
