'use client';

import { useEffect, useMemo, useState } from 'react';
import Link from 'next/link';
import { api, logout, post } from '../lib/api';
import { onNotification } from '../lib/realtime';

const money=(k=0)=>`₦${(Number(k)/100).toLocaleString('en-NG',{maximumFractionDigits:0})}`;

export default function RiderHome(){
  const [r,setR]=useState<any>(),[offers,setOffers]=useState<any[]>([]),[stats,setStats]=useState<any>({}),[current,setCurrent]=useState<any>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[loc,setLoc]=useState<any>(null);
  async function load(){try{const [me,o,s,c]=await Promise.all([api('/api/rider/me'),api('/api/rider/delivery-offers'),api('/api/rider/deliveries/stats'),api('/api/rider/current-delivery')]);setR(me);setOffers(o);setStats(s);setCurrent(c);setError('')}catch(e:any){setError(e.message||'Unable to load rider dashboard.')}}
  useEffect(()=>{load();const off=onNotification(n=>{if(n?.type==='DELIVERY'||n?.title==='New delivery offer') void load();});const t=setInterval(load,7000);return()=>{off();clearInterval(t)}},[]);
  useEffect(()=>{if(!r?.isOnline||!navigator.geolocation)return;let mounted=true;const push=()=>navigator.geolocation.getCurrentPosition(async p=>{if(!mounted)return;const next={latitude:p.coords.latitude,longitude:p.coords.longitude,accuracy:Math.round(p.coords.accuracy)};setLoc(next);try{await post('/api/rider/me/location',{latitude:next.latitude,longitude:next.longitude})}catch{}},()=>{}, {enableHighAccuracy:true,maximumAge:10000,timeout:8000});push();const t=setInterval(push,15000);return()=>{mounted=false;clearInterval(t)}},[r?.isOnline]);
  async function toggleOnline(){setBusy(true);setError('');try{if(!r?.isOnline){if(!navigator.geolocation)throw new Error('Location is required to go online.');const p=await new Promise<GeolocationPosition>((resolve,reject)=>navigator.geolocation.getCurrentPosition(resolve,reject,{enableHighAccuracy:true,timeout:10000}));await post('/api/rider/me/location',{latitude:p.coords.latitude,longitude:p.coords.longitude});setLoc({latitude:p.coords.latitude,longitude:p.coords.longitude,accuracy:Math.round(p.coords.accuracy)});await post('/api/rider/me/go-online')}else await post('/api/rider/me/go-offline');await load()}catch(e:any){setError(e.message||'Could not change availability.')}finally{setBusy(false)}}
  async function respond(id:string,action:'accept'|'decline'){setBusy(true);setError('');try{await post(`/api/rider/delivery-offers/${id}/${action}`);await load()}catch(e:any){setError(e.message||'This offer is no longer available.')}finally{setBusy(false)}}
  const canWork=r?.status==='APPROVED'||r?.status==='ACTIVE';
  const greeting=useMemo(()=>{const h=new Date().getHours();return h<12?'Good morning':h<18?'Good afternoon':'Good evening'},[]);
  return <div className="rider-app"><nav className="mobile-top"><Link className="brand" href="/">ROZZI <span>RIDER</span></Link><Link href="/notifications" className="icon-btn" aria-label="Notifications">⌁</Link></nav><aside className="side-nav"><div className="brand big">ROZZI <span>RIDER</span></div><p className="nav-label">WORKSPACE</p><Link className="active" href="/">⌂ <span>Home</span></Link><Link href="/deliveries">▣ <span>Deliveries</span></Link><Link href="/map">⌖ <span>Live Map</span></Link><Link href="/history">↺ <span>History</span></Link><p className="nav-label">MONEY</p><Link href="/earnings">₦ <span>Earnings</span></Link><Link href="/wallet">◉ <span>Wallet</span></Link><p className="nav-label">YOU</p><Link href="/performance">★ <span>Performance</span></Link><Link href="/advanced">✦ <span>Advanced ROZZI</span></Link><Link href="/profile">● <span>Profile</span></Link><Link href="/support">? <span>Support</span></Link><button className="logout-link" onClick={()=>{logout();location.href='/login'}}>↪ <span>Log out</span></button></aside><main className="rider-main"><header className="desktop-header"><div><span className="eyebrow">RIDER COMMAND CENTER</span><h1>{greeting}, {r?.owner?.fullName?.split(' ')[0]||'Rider'} 👋</h1><p>Everything you need to complete your next delivery.</p></div><div className="header-actions"><Link href="/notifications" className="icon-btn">⌁</Link><button disabled={busy||!r||!canWork} className={`online-toggle ${r?.isOnline?'online':'offline'}`} onClick={toggleOnline}><i/>{r?.isOnline?'ONLINE':'GO ONLINE'}</button></div></header>
  {error&&<div className="error">{error}</div>}
  {!canWork&&<div className="verification-banner"><div><b>Your rider account is {r?.status||'pending'}.</b><span>Complete verification before you can receive delivery requests.</span></div><Link href="/profile/verification">View verification</Link></div>}
  <section className="hero-grid"><div className="map-card"><div className="map-toolbar"><span className="map-live"><i/> LIVE MAP</span><Link href="/map">Open map →</Link></div><div className="map-stage"><div className="map-road r1"/><div className="map-road r2"/><div className="map-road r3"/><div className="map-zone zone1">HIGH DEMAND</div><div className="map-pin vendor-pin">⌂</div><div className="map-pin rider-pin">🛵</div><div className="map-label rider-label">You</div><div className="map-label vendor-label">Pickup</div><div className="map-bottom"><span>{loc?`GPS ±${loc.accuracy}m`:'Location not shared'}</span><span>{r?.isOnline?'Receiving offers':'Go online to receive offers'}</span></div></div></div><div className="today-panel"><div className="panel-title"><div><span className="eyebrow">TODAY</span><h2>Your shift</h2></div><span className={`mini-status ${r?.isOnline?'on':''}`}><i/>{r?.isOnline?'Online':'Offline'}</span></div><div className="big-earnings">{money(stats.totalDeliveryFees)}<small>delivery fees earned</small></div><div className="today-stats"><div><b>{stats.completedDeliveries||0}</b><span>Completed</span></div><div><b>{stats.activeDeliveries||0}</b><span>Active</span></div><div><b>{stats.averageDeliveryMinutes?`${stats.averageDeliveryMinutes}m`:'—'}</b><span>Avg. time</span></div></div><Link className="wide-btn" href="/earnings">View earnings</Link></div></section>
  {current&&<section className="active-delivery card"><div className="active-copy"><span className="eyebrow">ACTIVE DELIVERY</span><h2>{current.order?.orderNumber}</h2><p><b>{current.order?.vendor?.storeName||'Vendor'}</b> → {current.order?.address?.addressText||current.order?.address?.addressLine1||'Customer drop-off'}</p></div><div className="active-right"><span className="status-chip">{current.order?.status?.replaceAll('_',' ')}</span><Link className="wide-btn" href="/current">Continue delivery →</Link></div></section>}
  <section className="section-head"><div><span className="eyebrow">DISPATCH</span><h2>Delivery offers</h2><p>Choose a job that fits your route.</p></div><Link href="/deliveries">See all →</Link></section>
  {!offers.length?<div className="empty-state card"><div className="empty-icon">⌁</div><h3>{r?.isOnline?'Looking for deliveries…':'You are offline'}</h3><p>{r?.isOnline?'Stay nearby. New offers will appear automatically.':'Go online when you are ready to start receiving delivery requests.'}</p>{!r?.isOnline&&canWork&&<button className="wide-btn" onClick={toggleOnline}>Go online</button>}</div>:<div className="offer-grid">{offers.slice(0,3).map(x=><article className="offer-card card" key={x.id}><div className="offer-head"><div><span className="offer-kicker">NEW DELIVERY</span><b>{x.delivery?.order?.orderNumber||'Delivery'}</b></div><span className="countdown">{Math.max(0,Math.ceil((new Date(x.expiresAt).getTime()-Date.now())/1000))}s</span></div><h3>{x.delivery?.order?.vendor?.storeName||'ROZZI vendor'}</h3><p>{x.delivery?.order?.address?.addressText||x.delivery?.order?.address?.addressLine1||'Customer location'} · {x.distanceKm?`${Number(x.distanceKm).toFixed(1)} km to pickup`:'Distance unavailable'}</p><div className="offer-meta"><strong>{money(x.delivery?.order?.deliveryFeeAmount)}</strong><span>{x.delivery?.order?.items?.reduce((n:any,i:any)=>n+i.quantity,0)||0} items</span></div><div className="offer-actions"><button className="btn ghost" disabled={busy} onClick={()=>respond(x.id,'decline')}>Decline</button><button className="btn accept" disabled={busy} onClick={()=>respond(x.id,'accept')}>Accept delivery</button></div></article>)}</div>}
  </main><nav className="bottom-nav"><Link className="active" href="/">⌂<span>Home</span></Link><Link href="/map">⌖<span>Map</span></Link><Link href="/deliveries">▣<span>Orders</span></Link><Link href="/earnings">₦<span>Earnings</span></Link><Link href="/profile">●<span>Me</span></Link></nav></div>
}

