import { Injectable, ServiceUnavailableException } from '@nestjs/common'; import { ConfigService } from '@nestjs/config'; import { createHmac, timingSafeEqual } from 'crypto'; import { InitializePaymentParams,InitializePaymentResult,PaymentProvider,RefundResult,VerifyPaymentResult } from '../interfaces/payment-provider.interface';
const BASE='https://api.flutterwave.com/v3';
@Injectable() export class FlutterwaveAdapter implements PaymentProvider { readonly name='FLUTTERWAVE' as const; constructor(private readonly cfg:ConfigService){}
 private key(){const k=this.cfg.get<string>('FLUTTERWAVE_SECRET_KEY');if(!k)throw new ServiceUnavailableException('Flutterwave integration implemented but awaiting FLUTTERWAVE_SECRET_KEY.');return k;}
 async initialize(p:InitializePaymentParams):Promise<InitializePaymentResult>{const r=await fetch(`${BASE}/payments`,{method:'POST',headers:{Authorization:`Bearer ${this.key()}`,'Content-Type':'application/json'},body:JSON.stringify({tx_ref:p.reference,amount:(p.amountKobo/100).toFixed(2),currency:'NGN',redirect_url:p.callbackUrl||`${this.cfg.get<string>('CUSTOMER_APP_URL','http://localhost:3002').replace(/\/$/,'')}/payments/flutterwave/callback`,customer:{email:p.email},meta:p.metadata})});const b:any=await r.json();if(!r.ok||b.status!=='success')throw new ServiceUnavailableException(`Flutterwave initialization failed: ${b.message||r.statusText}`);return {authorizationUrl:b.data.link,reference:p.reference};}
 async verify(reference:string):Promise<VerifyPaymentResult>{throw new ServiceUnavailableException('Flutterwave verification requires the provider transaction id. Use the redirect transaction_id or webhook.');}
 async verifyTransactionId(id:string, expectedReference?:string):Promise<VerifyPaymentResult>{const r=await fetch(`${BASE}/transactions/${encodeURIComponent(id)}/verify`,{headers:{Authorization:`Bearer ${this.key()}`}});const b:any=await r.json();if(!r.ok||b.status!=='success')throw new ServiceUnavailableException(`Flutterwave verification failed: ${b.message||r.statusText}`);const d=b.data;if(expectedReference&&d.tx_ref!==expectedReference)throw new ServiceUnavailableException('Flutterwave transaction reference mismatch.');return {status:d.status==='successful'?'success':d.status==='failed'?'failed':d.status==='cancelled'?'abandoned':'pending',amountKobo:Math.round(Number(d.amount)*100),currency:d.currency,paidAt:d.created_at?new Date(d.created_at):undefined,raw:d};}
 verifyWebhookSignature(rawBody:Buffer|string,signatureHeader:string|undefined){const secret=this.cfg.get<string>('FLUTTERWAVE_WEBHOOK_SECRET_HASH');if(!secret||!signatureHeader)return false;const expected=createHmac('sha256',secret).update(rawBody).digest('base64');const a=Buffer.from(expected);const b=Buffer.from(signatureHeader.trim());return a.length===b.length&&timingSafeEqual(a,b);}
 async refund(reference:string,amountKobo?:number):Promise<RefundResult>{const r=await fetch(`${BASE}/transactions/${encodeURIComponent(reference)}/refund`,{method:'POST',headers:{Authorization:`Bearer ${this.key()}`,'Content-Type':'application/json'},body:JSON.stringify({amount:amountKobo?amountKobo/100:undefined})});const b:any=await r.json();if(!r.ok||b.status!=='success')return {status:'failed',raw:b};return {status:'pending',raw:b.data};}
}
