import { ConflictException, ForbiddenException, Injectable, NotFoundException } from '@nestjs/common';
import { PrismaService } from '../../config/prisma.service';
import { vendorForUser } from '../../common/utils/vendor-context'; import { AuditLogService } from '../audit/audit-log.service'; import { CreateOutletDto, UpdateOutletDto } from './dto/outlet.dto';
@Injectable() export class OutletsService {
 constructor(private readonly prisma:PrismaService,private readonly audit:AuditLogService){}
 private async vendor(ownerUserId:string){return vendorForUser(this.prisma, ownerUserId);}
 async list(ownerUserId:string){const v=await this.vendor(ownerUserId);return this.prisma.outlet.findMany({where:{vendorId:v.id},include:{hours:true,_count:{select:{products:true}}},orderBy:[{isActive:'desc'},{name:'asc'}]});}
 async get(ownerUserId:string,id:string){const v=await this.vendor(ownerUserId);const o=await this.prisma.outlet.findFirst({where:{id,vendorId:v.id},include:{hours:true,products:{include:{product:{select:{id:true,name:true,sku:true,isAvailable:true}}}},_count:{select:{products:true}}}});if(!o)throw new NotFoundException('Outlet not found.');return o;}
 async create(ownerUserId:string,d:CreateOutletDto){const v=await this.vendor(ownerUserId);const exists=await this.prisma.outlet.findFirst({where:{vendorId:v.id,name:{equals:d.name.trim(),mode:'insensitive'}}});if(exists)throw new ConflictException('An outlet with this name already exists.');const o=await this.prisma.outlet.create({data:{vendorId:v.id,name:d.name.trim(),address:d.address,phone:d.phone,email:d.email,latitude:d.latitude,longitude:d.longitude,deliveryRadiusKm:d.deliveryRadiusKm,minimumOrderAmount:d.minimumOrderAmount,averagePreparationTimeMinutes:d.averagePreparationTimeMinutes,isActive:d.isActive??true,isOpen:d.isOpen??false,operatingHoursJson:d.operatingHoursJson??undefined}});await this.audit.record({actorId:ownerUserId,action:'vendor.outlet.create',entityType:'Outlet',entityId:o.id,after:{name:o.name}});return o;}
 async update(ownerUserId:string,id:string,d:UpdateOutletDto){const before=await this.get(ownerUserId,id);if(d.name&&d.name.trim().toLowerCase()!==before.name.toLowerCase()){const exists=await this.prisma.outlet.findFirst({where:{vendorId:before.vendorId,name:{equals:d.name.trim(),mode:'insensitive'},NOT:{id}}});if(exists)throw new ConflictException('An outlet with this name already exists.');}const o=await this.prisma.outlet.update({where:{id},data:{...d,name:d.name?.trim()??undefined}});await this.audit.record({actorId:ownerUserId,action:'vendor.outlet.update',entityType:'Outlet',entityId:id,before:{name:before.name,isOpen:before.isOpen,isActive:before.isActive},after:{name:o.name,isOpen:o.isOpen,isActive:o.isActive}});return this.get(ownerUserId,id);}
 async setActive(ownerUserId:string,id:string,isActive:boolean){const o=await this.get(ownerUserId,id);if(!isActive&&o.isOpen)throw new ForbiddenException('Close the outlet before deactivating it.');return this.prisma.outlet.update({where:{id},data:{isActive}});}
 async setOpen(ownerUserId:string,id:string,isOpen:boolean){const o=await this.get(ownerUserId,id);if(isOpen&&!o.isActive)throw new ForbiddenException('Activate the outlet before opening it.');return this.prisma.outlet.update({where:{id},data:{isOpen}});}
 async assignProduct(ownerUserId:string,outletId:string,productId:string){const o=await this.get(ownerUserId,outletId);const p=await this.prisma.product.findFirst({where:{id:productId,vendorId:o.vendorId}});if(!p)throw new NotFoundException('Product not found.');return this.prisma.outletProduct.upsert({where:{outletId_productId:{outletId,productId}},update:{isActive:true},create:{outletId,productId,isActive:true}});}
 async unassignProduct(ownerUserId:string,outletId:string,productId:string){await this.get(ownerUserId,outletId);try{return await this.prisma.outletProduct.delete({where:{outletId_productId:{outletId,productId}}});}catch{throw new NotFoundException('Product is not assigned to this outlet.');}}
}

