import { Injectable, NotFoundException } from '@nestjs/common'; import { PrismaService } from '../../config/prisma.service'; import { AuditLogService } from '../audit/audit-log.service';
@Injectable() export class AdvertisingService { constructor(private readonly prisma:PrismaService,private readonly audit:AuditLogService){}
 async publicBanners(placement='HOME'){const now=new Date(); return this.prisma.banner.findMany({where:{placement,isActive:true,startsAt:{lte:now},endsAt:{gte:now}},orderBy:{displayOrder:'asc'}})}
 async publicAds(placement='HOME'){const now=new Date(); return this.prisma.advertisement.findMany({where:{placement,isActive:true,startsAt:{lte:now},endsAt:{gte:now}},orderBy:{displayOrder:'asc'}})}
 listBanners(){return this.prisma.banner.findMany({orderBy:[{placement:'asc'},{displayOrder:'asc'}]})} listAds(){return this.prisma.advertisement.findMany({orderBy:[{placement:'asc'},{displayOrder:'asc'}]})}
 async createBanner(d:any,actorId:string){const r=await this.prisma.banner.create({data:d});await this.audit.record({actorId,action:'banner.create',entityType:'Banner',entityId:r.id,after:r});return r}
 async updateBanner(id:string,d:any,actorId:string){const before=await this.prisma.banner.findUnique({where:{id}});if(!before)throw new NotFoundException('Banner not found.');const r=await this.prisma.banner.update({where:{id},data:d});await this.audit.record({actorId,action:'banner.update',entityType:'Banner',entityId:id,before,after:r});return r}
 async deleteBanner(id:string,actorId:string){const before=await this.prisma.banner.findUnique({where:{id}});if(!before)throw new NotFoundException('Banner not found.');await this.prisma.banner.delete({where:{id}});await this.audit.record({actorId,action:'banner.delete',entityType:'Banner',entityId:id,before});return {success:true}}
 async createAd(d:any,actorId:string){const r=await this.prisma.advertisement.create({data:d});await this.audit.record({actorId,action:'advertisement.create',entityType:'Advertisement',entityId:r.id,after:r});return r}
 async updateAd(id:string,d:any,actorId:string){const before=await this.prisma.advertisement.findUnique({where:{id}});if(!before)throw new NotFoundException('Advertisement not found.');const r=await this.prisma.advertisement.update({where:{id},data:d});await this.audit.record({actorId,action:'advertisement.update',entityType:'Advertisement',entityId:id,before,after:r});return r}
 async deleteAd(id:string,actorId:string){const before=await this.prisma.advertisement.findUnique({where:{id}});if(!before)throw new NotFoundException('Advertisement not found.');await this.prisma.advertisement.delete({where:{id}});await this.audit.record({actorId,action:'advertisement.delete',entityType:'Advertisement',entityId:id,before});return {success:true}}
 async impression(id:string){await this.prisma.advertisement.update({where:{id},data:{impressions:{increment:1}}});return {success:true}}
 async click(id:string){await this.prisma.advertisement.update({where:{id},data:{clicks:{increment:1}}});return {success:true}}
}
